      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-debug-apk
          path: '**/build/outputs/apk/debug/*.apk'
          if-no-files-found: error